name: unet_env
channels:
  - pytorch
  - fastai
  - defaults
  - conda-forge
  - awolny
dependencies:
  - fastai=1.0.61
  - h5py
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - numpy=1.18.5
  - pandas=1.0.4
  - pip
  - python
  - pytorch=1.4.0
  - pytorch-3dunet=1.2.12
  - scikit-image=0.17.2
  - scikit-learn=0.23.1
  - torchvision=0.5.0
  - tqdm=4.46.1
  - yaml=0.2.5
  - pip:
    - termplotlib==0.3.1
    - torchio==0.17.10

