name: unet_env
channels:
  - pytorch
  - fastai
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - appdirs=1.4.4
  - astroid=2.4.2
  - attrs=19.3.0
  - autopep8=1.5.3
  - beautifulsoup4=4.9.1
  - black=20.8b1
  - blosc=1.19.0
  - bottleneck=1.3.2
  - brotli=1.0.7
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - catalogue=1.0.0
  - certifi=2020.12.5
  - cffi=1.14.0
  - chardet=3.0.4
  - charls=2.1.0
  - click=7.1.2
  - cloudpickle=1.4.1
  - cryptography=2.9.2
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - cymem=2.0.3
  - cython-blis=0.4.1
  - cytoolz=0.10.1
  - dask-core=2.18.1
  - dataclasses=0.7
  - dbus=1.13.14
  - decorator=4.4.2
  - expat=2.2.9
  - fastai=1.0.61
  - fastprogress=0.2.3
  - flake8=3.8.3
  - fontconfig=2.13.1
  - freetype=2.10.2
  - giflib=5.2.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdbscan=0.8.26
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.9
  - imagecodecs=2020.5.30
  - imageio=2.8.0
  - importlib-metadata=1.6.1
  - importlib_metadata=1.6.1
  - intel-openmp=2020.1
  - isort=4.3.21
  - joblib=0.15.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jxrlib=1.1
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - lcms2=2.9
  - ld_impl_linux-64=2.34
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.9
  - libzopfli=1.0.3
  - lz4-c=1.9.2
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mkl=2020.1
  - murmurhash=1.0.2
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - networkx=2.4
  - ninja=1.10.0
  - numexpr=2.7.1
  - numpy=1.18.5
  - nvidia-ml-py3=7.352.0
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1j
  - packaging=20.4
  - pandas=1.0.4
  - pathspec=0.8.1
  - pcre=8.44
  - pillow=7.1.2
  - pip=20.1.1
  - plac=0.9.6
  - preshed=3.0.2
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pyflakes=2.2.0
  - pylint=2.5.3
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.4.0
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=8.0
  - regex=2020.11.13
  - requests=2.23.0
  - rope=0.17.0
  - scikit-image=0.17.2
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - setuptools=47.1.1
  - sip=4.19.13
  - six=1.15.0
  - snappy=1.1.8
  - soupsieve=2.0.1
  - spacy=2.2.4
  - sqlite=3.31.1
  - srsly=1.0.2
  - thinc=7.4.0
  - threadpoolctl=2.1.0
  - tifffile=2020.6.3
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.10.0
  - torchvision=0.5.0
  - tornado=6.0.4
  - tqdm=4.46.1
  - typed-ast=1.4.2
  - typing_extensions=3.7.4.3
  - urllib3=1.25.9
  - wasabi=0.6.0
  - wheel=0.34.2
  - wrapt=1.11.2
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - humanize==2.4.0
    - nibabel==3.1.0
    - python-deprecated==1.1.0
    - pytorch3dunet==1.2.12
    - simpleitk==1.2.4
    - termplotlib==0.3.1
    - torchio==0.17.2

